### ISSUE TITLE
Build fails looking for 'github.com/go-git/go-billy/v5/osfs'

### ISSUE THREAD

**Issue by simon-brooke** [augmentable-dev/askgit#37] opened 2020-08-16 11:33 UTC
Build log as follows:

```
simon@mason:~/tmp$ go get -v -tags=sqlite_vtable github.com/augmentable-dev/askgit
github.com/augmentable-dev/askgit (download)
github.com/go-git/go-git (download)
github.com/go-git/go-billy (download)
Fetching https://golang.org/x/sys/unix?go-get=1
Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
github.com/go-git/gcfg (download)
Fetching https://gopkg.in/warnings.v0?go-get=1
Parsing meta tags from https://gopkg.in/warnings.v0?go-get=1 (status code 200)
get "gopkg.in/warnings.v0": found meta tag get.metaImport{Prefix:"gopkg.in/warnings.v0", VCS:"git", RepoRoot:"https://gopkg.in/warnings.v0"} at https://gopkg.in/warnings.v0?go-get=1
gopkg.in/warnings.v0 (download)
github.com/mitchellh/go-homedir (download)
github.com/jbenet/go-context (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
github.com/emirpasic/gods (download)
github.com/sergi/go-diff (download)
Fetching https://golang.org/x/crypto/openpgp?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp?go-get=1 (status code 200)
get "golang.org/x/crypto/openpgp": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/openpgp?go-get=1
get "golang.org/x/crypto/openpgp": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
github.com/kevinburke/ssh_config (download)
github.com/xanzy/ssh-agent (download)
Fetching https://golang.org/x/crypto/ssh?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh?go-get=1
get "golang.org/x/crypto/ssh": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/ssh/knownhosts?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh/knownhosts?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh/knownhosts": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh/knownhosts?go-get=1
get "golang.org/x/crypto/ssh/knownhosts": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/proxy?go-get=1
Parsing meta tags from https://golang.org/x/net/proxy?go-get=1 (status code 200)
get "golang.org/x/net/proxy": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/proxy?go-get=1
get "golang.org/x/net/proxy": verifying non-authoritative meta tag
github.com/imdario/mergo (download)
github.com/mattn/go-sqlite3 (download)
github.com/gitsight/go-vcsurl (download)
github.com/olekukonko/tablewriter (download)
github.com/mattn/go-runewidth (download)
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
../go/src/github.com/go-git/go-git/remote.go:9:2: code in directory /home/simon/go/src/github.com/go-git/go-billy/osfs expects import "github.com/go-git/go-billy/v5/osfs"
```

On investigation, `https://github.com/go-git/go-billy/v5/osfs` does not exist but `https://github.com/go-git/go-billy/osfs` does. Suggest this is bit-rot caused by the upstream package changing its directory structure?

**Comment by patrickdevivo** [comment] 2020-09-02 02:16
Hi @simon-brooke - thanks for reporting this, I'm having difficulty reproducing. Could you share the version of go you are using, or perhaps try again as there have been some commits (I believe) modifying the package dependencies since this issue was opened?

**Comment by federico-razzoli** [comment] 2020-09-02 13:32
I reported a bug that was filed as a duplicate of this. In my case:

```
$ go version
go version go1.10.4 linux/amd64
```

**Comment by Vialeon** [comment] 2020-09-02 14:43
> I reported a bug that was filed as a duplicate of this. In my case:
> 
> ```
> $ go version
> go version go1.10.4 linux/amd64
> ```
@federico-razzoli 
The version the mod and sum are built on is go 1.13.(at least that is what the go.mod leads me to believe) If you update your system to version 1.13 or later it might fix the problem

**Closed** 2020-09-18 01:00 UTC
